apiVersion: v1
kind: Service
metadata:
  name: league-of-locals-user-api-svc
spec:
  type: NodePort
  selector:
    app: league-of-locals-user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080