name: Build and Deploy User API

# This workflow runs on every push to the main branch
on:
  push:
    branches: [ "main" ]

env:
  # The prefix for your container images
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  # Job 1: Build the code, create a Docker image, and push it to the registry
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/thefadedone/league-of-locals-user-api:${{ github.sha }}

        # In .github/workflows/main.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- DEBUGGING STEP 1 ---
      # This command will list every single file checked out onto the runner.
      # It will prove whether the 'kube' directory is there or not.
      - name: Verify that manifest files exist
        run: ls -R

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Create .kube directory for config
        run: mkdir -p ~/.kube

      - name: Save Kubeconfig
        run: doctl kubernetes cluster kubeconfig save league-of-locals-cluster

      # --- DEBUGGING STEP 2 ---
      # This verifies that we are successfully connected to your cluster.
      - name: Verify kubectl connection
        run: kubectl get nodes

      # --- THE DEPLOYMENT STEP ---
      # This is the command that was failing.
      - name: Deploy to DigitalOcean Kubernetes
        # IMPORTANT: Make sure the path here EXACTLY matches the folder name
        # shown in the "Verify that manifest files exist" step above.
        # If your folder is named ".kube", change it here.
        run: kubectl apply -f ./kube